[package]
name = "first_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
arabic_reshaper = "0.4.1"
unicode-segmentation = "1.9.0"
bevy-inspector-egui = "*"